name: PythonPackage
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: SetupPython
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"
    - name: InstallPackages
      run: pip install -r requirements.txt
    - name: RunTests
      run: python manage.py test
